### ISSUE TITLE
update to Leaflet 1.3.1

### ISSUE THREAD

**Issue by JackDougherty** [DataVizForAll/leaflet-storymaps-with-google-sheets#8]
@ilyankou - let's discuss this at our meeting with the new developer

https://github.com/DataVizForAll/leaflet-storymaps-with-google-sheets/blob/master/index.html#L8
and also update, if new versions available:
- leaflet-providers
- leaflet.extra-markers

**Comment by ilyankou** [comment]
Updated to Leaflet 1.3.1 -- now loading from Cloudflare (one of the most reliable CDNs). Updated jQuery to 3.3.1.
