### ISSUE TITLE
Overlay does not show

### ISSUE THREAD

**Issue by zoefSmoelt** [DataVizForAll/leaflet-storymaps-with-google-sheets#97]
Maybe I am doing something wrong, but if I place my own PNG and TIFF in the media-directory and place the link in the Sheet it does not show. I used a PNG and a TIFF which I exported from QGIS. After import them again they show up any the right place in QGIS.

**Comment by zoefSmoelt** [comment]
If I put the same file in Map Warper I get it working but I would like to use directly the PNG or TIFF out of QGIS because it is already geocoded. So the question is if that is possible and yes, how. By the way, thanks for the great work!

**Comment by JackDougherty** [comment]
As you probably read, we explained how to insert an XYZ link to georeferenced overlay map tiles in these HODV chapters: [Leaflet Storymaps with Google Sheets](https://github.com/OnTheLine/otl-public-housing#map-georeference-methods) and [Georeference with Map Warper](https://handsondataviz.org/mapwarper.html).

If you wish to use an alternative method, consider this strategy with QGIS and GitHub or other server to host tiles for your XYZ link:
- Georeference your map with QGIS
- QGIS Processing > Raster Tools to generate XYZ tiles into tiles folder
- Host folder and Leaflet code in repo using GitHub Pages, or choose another server.

See this example
https://github.com/OnTheLine/otl-public-housing#map-georeference-methods

**Comment by zoefSmoelt** [comment]
Thanks! After some experimenting ands correcting typos I made I got it working.
