### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by sasignell** [DataVizForAll/leaflet-storymaps-with-google-sheets#98]
Getting an error relating to turning overlays on and off in the newest version: 
`Uncaught TypeError: Cannot use 'in' operator to search for '_leaflet_id' in undefined`
Looks like the  code  in lines 313-320 is causing the trouble

**Comment by ilyankou** [comment]
Thank you for spotting this @sasignell 

I believe the error was introduced when we bumped Leaflet version from 1.7.1. to 1.9.4. Previously it used to handle `map.hasLayer(undefined)` just fine, but in the new version it results in an error.

Should be fixed now!
